[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10" 
lazy_static = "1.4" 
tch = "0.12" 

# Optional: For parsing story data from a file (e.g., JSON)
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"